<%@ Page Language="vb" AutoEventWireup="false" Codebehind="WebForm3.aspx.vb" Inherits="Qahili.WebForm3"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
	<HEAD>
		<title>WebForm3</title>
		<meta content="Microsoft Visual Studio .NET 7.1" name="GENERATOR">
		<meta content="Visual Basic .NET 7.1" name="CODE_LANGUAGE">
		<meta content="JavaScript" name="vs_defaultClientScript">
		<meta content="http://schemas.microsoft.com/intellisense/ie5" name="vs_targetSchema">
	</HEAD>
	<body bgColor="gainsboro" MS_POSITIONING="GridLayout">
		<form id="Form1" method="post" runat="server">
			<asp:label id="Label1" style="Z-INDEX: 100; LEFT: 496px; POSITION: absolute; TOP: 16px" runat="server"
				ForeColor="DimGray" BackColor="LightGray" BorderColor="LightGray" BorderStyle="Inset" BorderWidth="2px"
				Font-Bold="True" Font-Size="X-Large" Height="48px" Width="240px">The I.B.C Bank</asp:label><asp:textbox id="Textbox28" style="Z-INDEX: 186; LEFT: 16px; POSITION: absolute; TOP: 920px"
				runat="server" Width="168px"></asp:textbox><asp:label id="Label34" style="Z-INDEX: 185; LEFT: 344px; POSITION: absolute; TOP: 768px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">Balance</asp:label><asp:textbox id="Textbox27" style="Z-INDEX: 184; LEFT: 432px; POSITION: absolute; TOP: 768px"
				runat="server" Width="128px"></asp:textbox><asp:button id="Button7" style="Z-INDEX: 183; LEFT: 632px; POSITION: absolute; TOP: 96px" runat="server"
				ForeColor="White" BackColor="#C00000" BorderColor="Maroon" BorderStyle="Inset" Font-Bold="True" Width="97px" Text="Dashboard"></asp:button><asp:requiredfieldvalidator id="RequiredFieldValidator18" style="Z-INDEX: 182; LEFT: 272px; POSITION: absolute; TOP: 840px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox26"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator17" style="Z-INDEX: 181; LEFT: 560px; POSITION: absolute; TOP: 840px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox25"></asp:requiredfieldvalidator><asp:label id="Label36" style="Z-INDEX: 180; LEFT: 32px; POSITION: absolute; TOP: 848px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">Username</asp:label><asp:label id="Label35" style="Z-INDEX: 179; LEFT: 344px; POSITION: absolute; TOP: 840px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">Password</asp:label><asp:textbox id="TextBox26" style="Z-INDEX: 177; LEFT: 136px; POSITION: absolute; TOP: 840px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox25" style="Z-INDEX: 176; LEFT: 424px; POSITION: absolute; TOP: 840px"
				runat="server" Width="128px"></asp:textbox><asp:label id="Label33" style="Z-INDEX: 175; LEFT: 16px; POSITION: absolute; TOP: 808px" runat="server"
				Font-Bold="True" Height="24px" Width="144px" Font-Italic="True">Login Details</asp:label><asp:requiredfieldvalidator id="RequiredFieldValidator16" style="Z-INDEX: 174; LEFT: 280px; POSITION: absolute; TOP: 288px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox2"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator15" style="Z-INDEX: 173; LEFT: 280px; POSITION: absolute; TOP: 248px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox5"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator14" style="Z-INDEX: 172; LEFT: 568px; POSITION: absolute; TOP: 136px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox9"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator13" style="Z-INDEX: 171; LEFT: 568px; POSITION: absolute; TOP: 168px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox8"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator12" style="Z-INDEX: 170; LEFT: 568px; POSITION: absolute; TOP: 216px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox7"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator11" style="Z-INDEX: 169; LEFT: 280px; POSITION: absolute; TOP: 216px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox4"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator10" style="Z-INDEX: 168; LEFT: 280px; POSITION: absolute; TOP: 168px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox3"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator9" style="Z-INDEX: 167; LEFT: 280px; POSITION: absolute; TOP: 136px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox1"></asp:requiredfieldvalidator><asp:label id="Label32" style="Z-INDEX: 166; LEFT: 320px; POSITION: absolute; TOP: 248px" runat="server"
				Font-Bold="True" Height="16px" Width="96px">Husband's N.</asp:label><asp:label id="Label31" style="Z-INDEX: 165; LEFT: 344px; POSITION: absolute; TOP: 208px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">Sex</asp:label><asp:label id="Label30" style="Z-INDEX: 164; LEFT: 344px; POSITION: absolute; TOP: 168px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">LName</asp:label><asp:label id="Label29" style="Z-INDEX: 163; LEFT: 344px; POSITION: absolute; TOP: 128px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">Title</asp:label><asp:label id="Label28" style="Z-INDEX: 162; LEFT: 24px; POSITION: absolute; TOP: 288px" runat="server"
				Font-Bold="True" Height="16px" Width="105px">Maritial Status</asp:label><asp:label id="Label27" style="Z-INDEX: 161; LEFT: 32px; POSITION: absolute; TOP: 248px" runat="server"
				Font-Bold="True" Height="16px" Width="80px">Father's N.</asp:label><asp:label id="Label26" style="Z-INDEX: 160; LEFT: 32px; POSITION: absolute; TOP: 208px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">D.O.B</asp:label><asp:label id="Label25" style="Z-INDEX: 159; LEFT: 32px; POSITION: absolute; TOP: 168px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">FName</asp:label><asp:label id="Label24" style="Z-INDEX: 158; LEFT: 32px; POSITION: absolute; TOP: 128px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">ID</asp:label><asp:requiredfieldvalidator id="RequiredFieldValidator8" style="Z-INDEX: 156; LEFT: 576px; POSITION: absolute; TOP: 376px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox15"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator7" style="Z-INDEX: 155; LEFT: 576px; POSITION: absolute; TOP: 416px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox13"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator6" style="Z-INDEX: 154; LEFT: 280px; POSITION: absolute; TOP: 456px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox12"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator5" style="Z-INDEX: 153; LEFT: 280px; POSITION: absolute; TOP: 408px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox14"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator4" style="Z-INDEX: 152; LEFT: 280px; POSITION: absolute; TOP: 488px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox10"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator1" style="Z-INDEX: 151; LEFT: 280px; POSITION: absolute; TOP: 376px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox16"></asp:requiredfieldvalidator><asp:label id="Label23" style="Z-INDEX: 150; LEFT: 352px; POSITION: absolute; TOP: 448px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">Email</asp:label><asp:label id="Label22" style="Z-INDEX: 149; LEFT: 352px; POSITION: absolute; TOP: 408px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">Pincode</asp:label><asp:label id="Label21" style="Z-INDEX: 148; LEFT: 352px; POSITION: absolute; TOP: 368px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">Street</asp:label><asp:label id="Label20" style="Z-INDEX: 147; LEFT: 32px; POSITION: absolute; TOP: 488px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">Mobile</asp:label><asp:label id="Label19" style="Z-INDEX: 146; LEFT: 32px; POSITION: absolute; TOP: 456px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">Country</asp:label><asp:label id="Label18" style="Z-INDEX: 145; LEFT: 32px; POSITION: absolute; TOP: 416px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">City</asp:label><asp:label id="Label17" style="Z-INDEX: 144; LEFT: 32px; POSITION: absolute; TOP: 376px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">House No.</asp:label><asp:label id="Label16" style="Z-INDEX: 143; LEFT: 32px; POSITION: absolute; TOP: 568px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">PAN No.</asp:label><asp:label id="Label15" style="Z-INDEX: 142; LEFT: 32px; POSITION: absolute; TOP: 608px" runat="server"
				Font-Bold="True" Height="16px" Width="88px">Passport No.</asp:label><asp:label id="Label3" style="Z-INDEX: 141; LEFT: 352px; POSITION: absolute; TOP: 568px" runat="server"
				Font-Bold="True" Height="16px" Width="72px"> AadharNo.</asp:label><asp:requiredfieldvalidator id="RequiredFieldValidator3" style="Z-INDEX: 140; LEFT: 576px; POSITION: absolute; TOP: 696px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox21"></asp:requiredfieldvalidator><asp:label id="Label14" style="Z-INDEX: 138; LEFT: 32px; POSITION: absolute; TOP: 728px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">Credit No.</asp:label><asp:label id="Label13" style="Z-INDEX: 137; LEFT: 344px; POSITION: absolute; TOP: 688px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">Branch</asp:label><asp:label id="Label12" style="Z-INDEX: 136; LEFT: 344px; POSITION: absolute; TOP: 728px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">Debit No.</asp:label><asp:label id="Label11" style="Z-INDEX: 135; LEFT: 32px; POSITION: absolute; TOP: 768px" runat="server"
				Font-Bold="True" Height="16px" Width="88px">Cheque No.</asp:label><asp:label id="Label9" style="Z-INDEX: 133; LEFT: 8px; POSITION: absolute; TOP: 952px" runat="server"
				ForeColor="White" BackColor="#404040" BorderColor="Black" BorderStyle="Inset" BorderWidth="2px" Font-Bold="True" Font-Size="Small" Height="24px" Width="736px">Terms & Conditions | Disclaimer | Policies</asp:label><asp:label id="Label8" style="Z-INDEX: 132; LEFT: 560px; POSITION: absolute; TOP: 920px" runat="server"
				ForeColor="White" BackColor="#8080FF" BorderColor="#0000C0" BorderStyle="Inset" BorderWidth="2px" Font-Bold="True" Font-Size="Small" Height="24px" Width="176px">Contact : 1800-1800-234</asp:label><asp:button id="Button2" style="Z-INDEX: 131; LEFT: 584px; POSITION: absolute; TOP: 872px" runat="server"
				ForeColor="White" BackColor="YellowGreen" BorderColor="Green" BorderStyle="Inset" BorderWidth="2px" Font-Bold="True" Height="40px" Width="144px" Text="Submit"></asp:button><asp:textbox id="TextBox24" style="Z-INDEX: 130; LEFT: 136px; POSITION: absolute; TOP: 688px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox23" style="Z-INDEX: 129; LEFT: 136px; POSITION: absolute; TOP: 728px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox22" style="Z-INDEX: 128; LEFT: 136px; POSITION: absolute; TOP: 768px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox21" style="Z-INDEX: 127; LEFT: 432px; POSITION: absolute; TOP: 688px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox20" style="Z-INDEX: 126; LEFT: 432px; POSITION: absolute; TOP: 728px"
				runat="server" Width="128px"></asp:textbox><asp:label id="Label7" style="Z-INDEX: 125; LEFT: 8px; POSITION: absolute; TOP: 648px" runat="server"
				Font-Bold="True" Height="24px" Width="144px" Font-Italic="True">Accounts Details</asp:label><asp:textbox id="TextBox19" style="Z-INDEX: 124; LEFT: 136px; POSITION: absolute; TOP: 568px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox18" style="Z-INDEX: 123; LEFT: 432px; POSITION: absolute; TOP: 568px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox17" style="Z-INDEX: 122; LEFT: 136px; POSITION: absolute; TOP: 608px"
				runat="server" Width="128px"></asp:textbox><asp:label id="Label6" style="Z-INDEX: 121; LEFT: 8px; POSITION: absolute; TOP: 536px" runat="server"
				Font-Bold="True" Height="24px" Width="144px" Font-Italic="True">Identification Details</asp:label><asp:textbox id="TextBox16" style="Z-INDEX: 120; LEFT: 136px; POSITION: absolute; TOP: 368px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox15" style="Z-INDEX: 119; LEFT: 432px; POSITION: absolute; TOP: 368px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox14" style="Z-INDEX: 118; LEFT: 136px; POSITION: absolute; TOP: 408px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox13" style="Z-INDEX: 117; LEFT: 432px; POSITION: absolute; TOP: 408px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox12" style="Z-INDEX: 116; LEFT: 136px; POSITION: absolute; TOP: 448px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox11" style="Z-INDEX: 115; LEFT: 432px; POSITION: absolute; TOP: 448px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox10" style="Z-INDEX: 114; LEFT: 136px; POSITION: absolute; TOP: 488px"
				runat="server" Width="128px"></asp:textbox><asp:label id="Label4" style="Z-INDEX: 113; LEFT: 8px; POSITION: absolute; TOP: 336px" runat="server"
				Font-Bold="True" Height="24px" Width="144px" Font-Italic="True">Contact Details</asp:label><asp:textbox id="TextBox9" style="Z-INDEX: 112; LEFT: 424px; POSITION: absolute; TOP: 128px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox8" style="Z-INDEX: 111; LEFT: 424px; POSITION: absolute; TOP: 168px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox7" style="Z-INDEX: 110; LEFT: 424px; POSITION: absolute; TOP: 208px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox6" style="Z-INDEX: 109; LEFT: 424px; POSITION: absolute; TOP: 248px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox5" style="Z-INDEX: 108; LEFT: 136px; POSITION: absolute; TOP: 248px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox4" style="Z-INDEX: 107; LEFT: 136px; POSITION: absolute; TOP: 208px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox3" style="Z-INDEX: 106; LEFT: 136px; POSITION: absolute; TOP: 168px"
				runat="server" Width="128px"></asp:textbox><asp:textbox id="TextBox2" style="Z-INDEX: 105; LEFT: 136px; POSITION: absolute; TOP: 288px"
				runat="server" Width="128px"></asp:textbox><asp:label id="Label5" style="Z-INDEX: 102; LEFT: 8px; POSITION: absolute; TOP: 40px" runat="server"
				ForeColor="White" BackColor="#8080FF" BorderColor="#0000C0" BorderStyle="Inset" BorderWidth="2px" Font-Bold="True" Font-Size="Small" Height="24px"
				Width="192px">New Customer Registration</asp:label>
			<HR style="Z-INDEX: 101; LEFT: 8px; WIDTH: 99.53%; POSITION: absolute; TOP: 72px; HEIGHT: 8px"
				width="99.53%" SIZE="8">
			<asp:textbox id="TextBox1" style="Z-INDEX: 103; LEFT: 136px; POSITION: absolute; TOP: 128px"
				runat="server" Width="128px"></asp:textbox><asp:label id="Label2" style="Z-INDEX: 104; LEFT: 16px; POSITION: absolute; TOP: 88px" runat="server"
				Font-Bold="True" Height="24px" Width="144px" Font-Italic="True">Personal Details</asp:label><asp:label id="Label10" style="Z-INDEX: 134; LEFT: 32px; POSITION: absolute; TOP: 688px" runat="server"
				Font-Bold="True" Height="16px" Width="72px">Acc No.</asp:label><asp:requiredfieldvalidator id="RequiredFieldValidator2" style="Z-INDEX: 139; LEFT: 280px; POSITION: absolute; TOP: 696px"
				runat="server" Height="16px" Width="32px" ErrorMessage="*" ControlToValidate="TextBox24"></asp:requiredfieldvalidator><asp:regularexpressionvalidator id="RegularExpressionValidator1" style="Z-INDEX: 157; LEFT: 576px; POSITION: absolute; TOP: 448px"
				runat="server" Width="24px" Height="16px" ControlToValidate="TextBox11" ErrorMessage="RegularExpressionValidator" ValidationExpression="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*">Invalid</asp:regularexpressionvalidator></form>
	</body>
</HTML>
